
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-atletismo
  namespace: p2-so1-2024
spec:
  selector:
    matchLabels:
      app: grpc-server-atletismo
  template:
    metadata:
      labels:
        app: grpc-server-atletismo
    spec:
      containers:
      - name: grpc-server-atletismo
        image: jhonsagui81/natacion:v4
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.3"
        ports:
        - containerPort: 50051
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: atletismo-hpa
  namespace: p2-so1-2024
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-server-atletismo
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 35

---
apiVersion: v1
kind: Service
metadata:
  name: athletics-service #DNS
  namespace: p2-so1-2024
spec:
  selector:
    app: grpc-server-atletismo
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
