apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: winners
  namespace: p2-so1-2024
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: losers
  namespace: p2-so1-2024
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
